/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.json.Json;
import javax.json.JsonArrayBuilder;
import javax.json.JsonBuilderFactory;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Lefos
 */
public class SystemFrame extends javax.swing.JFrame {

    /**
     * Creates new form SystemFrame
     */
    public SystemFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpanel = new javax.swing.JTabbedPane();
        addquestion = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        answer = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adduser = new javax.swing.JPanel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        addexamcenter = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addexamc = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        addadmincenter = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        addac = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        adctxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JTextField();
        addexam = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        ectxt = new javax.swing.JTextField();
        addexambut = new javax.swing.JButton();
        datetxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        reports = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        resultsexamid = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        examidtxt = new javax.swing.JTextField();
        resexamidbut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        resultsexamc = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        getecbut = new javax.swing.JButton();
        examcenters = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        showdatesbut = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        dates = new javax.swing.JComboBox<>();
        resecbut = new javax.swing.JButton();
        resultsalexams = new javax.swing.JPanel();
        showallbut = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        resultsexaminee = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        examineebut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin System");
        setMaximumSize(new java.awt.Dimension(700, 700));

        addquestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.darkGray, null, null));
        addquestion.setMaximumSize(new java.awt.Dimension(1000, 1000));
        addquestion.setPreferredSize(new java.awt.Dimension(663, 663));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));

        answer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True", "False" }));
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });

        jLabel2.setText("Answer");

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel1.setText("Question");

        jLayeredPane1.setLayer(answer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(question, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(submit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {answer, jLabel1, submit});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap())
        );

        javax.swing.GroupLayout addquestionLayout = new javax.swing.GroupLayout(addquestion);
        addquestion.setLayout(addquestionLayout);
        addquestionLayout.setHorizontalGroup(
            addquestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addquestionLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        addquestionLayout.setVerticalGroup(
            addquestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addquestionLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(731, Short.MAX_VALUE))
        );

        tpanel.addTab("Add Question", addquestion);

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));

        jLabel3.setText("Username");

        button.setText("Submit");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jLabel4.setText("Password");

        jLayeredPane5.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(username, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button)
                    .addGroup(jLayeredPane5Layout.createSequentialGroup()
                        .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button)
                .addContainerGap())
        );

        javax.swing.GroupLayout adduserLayout = new javax.swing.GroupLayout(adduser);
        adduser.setLayout(adduserLayout);
        adduserLayout.setHorizontalGroup(
            adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adduserLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        adduserLayout.setVerticalGroup(
            adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adduserLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(732, Short.MAX_VALUE))
        );

        tpanel.addTab("Add User", adduser);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));

        jLabel5.setText("Name");

        jLabel6.setText("Address");

        addexamc.setText("submit");
        addexamc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addexamcActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(addexamc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(address, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addexamc)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(42, 42, 42)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addexamc)
                .addContainerGap())
        );

        javax.swing.GroupLayout addexamcenterLayout = new javax.swing.GroupLayout(addexamcenter);
        addexamcenter.setLayout(addexamcenterLayout);
        addexamcenterLayout.setHorizontalGroup(
            addexamcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addexamcenterLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        addexamcenterLayout.setVerticalGroup(
            addexamcenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addexamcenterLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(728, Short.MAX_VALUE))
        );

        tpanel.addTab("Add Exam Center", addexamcenter);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));

        jLabel8.setText("Password");

        addac.setText("submit");
        addac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addacActionPerformed(evt);
            }
        });

        jLabel7.setText("Username");

        jLabel9.setText("Admin Center id");

        jLayeredPane3.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(addac, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(adctxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(usertxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(passtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addac)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(30, 30, 30)))
                        .addGap(32, 32, 32)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adctxt)
                            .addComponent(passtxt)
                            .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(adctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addac)
                .addContainerGap())
        );

        javax.swing.GroupLayout addadmincenterLayout = new javax.swing.GroupLayout(addadmincenter);
        addadmincenter.setLayout(addadmincenterLayout);
        addadmincenterLayout.setHorizontalGroup(
            addadmincenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addadmincenterLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        addadmincenterLayout.setVerticalGroup(
            addadmincenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addadmincenterLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(719, Short.MAX_VALUE))
        );

        tpanel.addTab("Add Admin Center", addadmincenter);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));

        jLabel11.setText("Exam Center id");

        addexambut.setText("submit");
        addexambut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addexambutActionPerformed(evt);
            }
        });

        jLabel10.setText("Date");

        jLayeredPane4.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ectxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(addexambut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(datetxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addexambut)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ectxt)
                            .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ectxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addexambut)
                .addContainerGap())
        );

        javax.swing.GroupLayout addexamLayout = new javax.swing.GroupLayout(addexam);
        addexam.setLayout(addexamLayout);
        addexamLayout.setHorizontalGroup(
            addexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addexamLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        addexamLayout.setVerticalGroup(
            addexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addexamLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(721, Short.MAX_VALUE))
        );

        tpanel.addTab("Add Exam", addexam);

        jLabel12.setText("Exam id");

        resexamidbut.setText("Submit");
        resexamidbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resexamidbutActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Question Id", "Answer", "True Answer", "Time", "Exam Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout resultsexamidLayout = new javax.swing.GroupLayout(resultsexamid);
        resultsexamid.setLayout(resultsexamidLayout);
        resultsexamidLayout.setHorizontalGroup(
            resultsexamidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addGroup(resultsexamidLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addGroup(resultsexamidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resexamidbut)
                    .addGroup(resultsexamidLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(26, 26, 26)
                        .addComponent(examidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resultsexamidLayout.setVerticalGroup(
            resultsexamidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsexamidLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(resultsexamidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(examidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resexamidbut)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Results based on exam id", resultsexamid);

        resultsexamc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resultsexamcFocusGained(evt);
            }
        });

        jLabel13.setText("Exam Center");

        getecbut.setBackground(new java.awt.Color(102, 255, 51));
        getecbut.setText("Get Exam Centers");
        getecbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getecbutActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Question Id", "Answer", "True Answer", "Time", "Exam Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table1);

        showdatesbut.setText("Show Dates");
        showdatesbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdatesbutActionPerformed(evt);
            }
        });

        jLabel14.setText("Dates");

        resecbut.setText("Submit");
        resecbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resecbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resultsexamcLayout = new javax.swing.GroupLayout(resultsexamc);
        resultsexamc.setLayout(resultsexamcLayout);
        resultsexamcLayout.setHorizontalGroup(
            resultsexamcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsexamcLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(resultsexamcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(getecbut))
                .addGap(18, 18, 18)
                .addGroup(resultsexamcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examcenters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showdatesbut))
                .addGap(146, 146, 146)
                .addGroup(resultsexamcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultsexamcLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resecbut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        resultsexamcLayout.setVerticalGroup(
            resultsexamcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsexamcLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(resultsexamcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(examcenters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(resultsexamcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getecbut)
                    .addComponent(showdatesbut)
                    .addComponent(resecbut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(430, 430, 430))
        );

        jTabbedPane1.addTab("Results based on exam center", resultsexamc);

        showallbut.setText("Show all");
        showallbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showallbutActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Question Id", "Answer", "True Answer", "Time", "Exam Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table2);

        javax.swing.GroupLayout resultsalexamsLayout = new javax.swing.GroupLayout(resultsalexams);
        resultsalexams.setLayout(resultsalexamsLayout);
        resultsalexamsLayout.setHorizontalGroup(
            resultsalexamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsalexamsLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(showallbut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(resultsalexamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
        );
        resultsalexamsLayout.setVerticalGroup(
            resultsalexamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsalexamsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(showallbut)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Results of all exams", resultsalexams);

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Question Id", "Answer", "True Answer", "Time", "Exam Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(table3);

        jLabel15.setText("Username");

        examineebut.setText("Show");
        examineebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examineebutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resultsexamineeLayout = new javax.swing.GroupLayout(resultsexaminee);
        resultsexaminee.setLayout(resultsexamineeLayout);
        resultsexamineeLayout.setHorizontalGroup(
            resultsexamineeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsexamineeLayout.createSequentialGroup()
                .addGroup(resultsexamineeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultsexamineeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
                    .addGroup(resultsexamineeLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(resultsexamineeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(examineebut)
                            .addGroup(resultsexamineeLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(26, 26, 26)
                                .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        resultsexamineeLayout.setVerticalGroup(
            resultsexamineeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsexamineeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(resultsexamineeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(examineebut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Results of an examinee", resultsexaminee);

        javax.swing.GroupLayout reportsLayout = new javax.swing.GroupLayout(reports);
        reports.setLayout(reportsLayout);
        reportsLayout.setHorizontalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        reportsLayout.setVerticalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tpanel.addTab("Reports", reports);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpanel)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(663, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        
    }//GEN-LAST:event_answerActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            String quest=question.getText();
            String ans=(String)answer.getSelectedItem();
            quest=quest.replace(" ","%20");
            String redirectURL = "http://localhost:8080/service/webresources/tryto/addq/"+quest+"/"+ans;
            URL oracle = new URL(redirectURL);
            BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
            String result,total="";
            while ((result = in.readLine()) != null)
            {
                total+=result;
            }  
            JSONArray arr = new JSONArray(total);
            String flag="0";
            for (int i = 0; i < arr.length(); i++)
            { // Walk through the Array.
                JSONObject obj = arr.getJSONObject(i);
                flag = obj.getString("flag");
            }  
            System.out.println(flag);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        try {
            String user= username.getText();
            String pass= password.getText();
            String redirectURL = "http://localhost:8080/service/webresources/tryto/addu/"+user+"/"+pass;
            URL oracle = new URL(redirectURL);
            BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
            String result,total="";
            while ((result = in.readLine()) != null)
            {
                total+=result;
            } 
            JSONArray arr = new JSONArray(total);
            String flag="0";
            for (int i = 0; i < arr.length(); i++)
            { // Walk through the Array.
                JSONObject obj = arr.getJSONObject(i);
                flag = obj.getString("flag");
            }  
            System.out.println(flag);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void addexamcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addexamcActionPerformed
        try {
            String nm=name.getText();
            String addr=address.getText();
            nm=nm.replace(" ","%20");
            addr=addr.replace(" ","%20");
            String redirectURL = "http://localhost:8080/service/webresources/tryto/addex/"+nm+"/"+addr;
            URL oracle = new URL(redirectURL);
            BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
            String result,total="";
            while ((result = in.readLine()) != null)
            {
                total+=result;
            }
            JSONArray arr = new JSONArray(total);
            String flag="0";
            for (int i = 0; i < arr.length(); i++)
            { // Walk through the Array.
                JSONObject obj = arr.getJSONObject(i);
                flag = obj.getString("flag");
            }
            System.out.println(flag);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addexamcActionPerformed

    private void addacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addacActionPerformed
        try {
            String username = usertxt.getText();
            String password = passtxt.getText();
            String admincid = adctxt.getText();
            //out.println(objq.question + " " + objq.answer);
            String redirectURL = "http://localhost:8080/service/webresources/tryto/addac/"+username+"/"+password+"/"+admincid;
            URL oracle = new URL(redirectURL);
            BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
            String result,total="";
            while ((result = in.readLine()) != null)
            {
                total+=result;
            }  
            JSONArray arr = new JSONArray(total);
            String flag="0";
            for (int i = 0; i < arr.length(); i++)
            { // Walk through the Array.
                JSONObject obj = arr.getJSONObject(i);
                flag = obj.getString("flag");
            }  
            System.out.println(flag);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addacActionPerformed

    private void addexambutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addexambutActionPerformed
        try {
            String date = datetxt.getText();
            String centerid = ectxt.getText();
            date=date.replace(" ","%20");
            //out.println(date+" "+ centerid);
            
            String redirectURL = "http://localhost:8080/service/webresources/tryto/addt/"+date+"/"+centerid;
            URL oracle = new URL(redirectURL);
            BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
            String result,total="";
            while ((result = in.readLine()) != null)
            {
                total+=result;
            }  JSONArray arr = new JSONArray(total);
            String flag="0";
            for (int i = 0; i < arr.length(); i++)
            { // Walk through the Array.
                JSONObject obj = arr.getJSONObject(i);
                flag = obj.getString("flag");
            }  System.out.println(flag);
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addexambutActionPerformed

    private void resexamidbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resexamidbutActionPerformed
        try {
            String examid = examidtxt.getText();
            JsonBuilderFactory factory = Json.createBuilderFactory(null);
            JsonArrayBuilder jsonA = factory.createArrayBuilder();
            jsonA = jsonA.add(factory.createObjectBuilder()
                    .add("exam_id",examid)
            );
            String test=jsonA.build().toString();
            test=test.replace("{", "%7B");
            test=test.replace("}", "%7D");
            URL oracle = new URL("http://localhost:8080/service/webresources/reports/rae/"+test);
            BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
            String result,total="";
            while ((result = in.readLine()) != null)
            {
                total+=result;
            }
            String username=null,idq=null,answer=null,trueanswer=null,time=null;
            JSONArray arr = new JSONArray(total);
            
            DefaultTableModel dtm = new DefaultTableModel(0, 0);
            String header[] = new String[] { "Username", "Question ID", "Answer",
            "True Answer", "Time", "Exam Id" };
            dtm.setColumnIdentifiers(header);
            table.setModel(dtm);
            
            for (int i = 0; i < arr.length(); i++)
            { // Walk through the Array.
                
                JSONObject obj = arr.getJSONObject(i);
                username=obj.getString("username");
                idq=obj.getString("idq");
                answer=obj.getString("answer");
                trueanswer=obj.getString("trueanswer");
                time=obj.getString("time");
                dtm.addRow(new Object[] { username, idq, answer,
                trueanswer, time, examid });
                
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_resexamidbutActionPerformed

    private void resultsexamcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resultsexamcFocusGained
        
    }//GEN-LAST:event_resultsexamcFocusGained

    private void getecbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getecbutActionPerformed
        try {
            examcenters.removeAllItems();
            URL oracle = new URL("http://localhost:8080/service/webresources/reports/getec");
            BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
            String result,total="";
            while ((result = in.readLine()) != null)
            {
                total+=result;
            }
            
            JSONArray arr = new JSONArray(total);
            for (int i = 0; i < arr.length(); i++) 
            { // Walk through the Array.

                JSONObject obj = arr.getJSONObject(i);
                String item= obj.getString("id") + ":" + obj.getString("name");
                examcenters.addItem(item);
                        
            }     
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_getecbutActionPerformed

    private void showdatesbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdatesbutActionPerformed
        try {
            if(examcenters.getItemCount()!=0)
            {
                dates.removeAllItems();
                String info=(String)examcenters.getSelectedItem();
                String[] data= info.split(":");
                String cid=data[0];
                JsonBuilderFactory factory = Json.createBuilderFactory(null);
                JsonArrayBuilder jsonA = factory.createArrayBuilder();
                jsonA = jsonA.add(factory.createObjectBuilder()
                        .add("cid",cid)
                );  String test=jsonA.build().toString();
                test=test.replace("{", "%7B");
                test=test.replace("}", "%7D");
                URL oracle = new URL("http://localhost:8080/service/webresources/reports/getdates/"+test);
                BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
                String result,total="";
                while ((result = in.readLine()) != null)
                {
                    total+=result;
                }

                JSONArray arr = new JSONArray(total);
                for (int i = 0; i < arr.length(); i++) 
                { // Walk through the Array.

                    JSONObject obj = arr.getJSONObject(i);
                    String item=obj.getString("id")+":"+" "+ ":" + obj.getString("date");
                    dates.addItem(item);

                }
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_showdatesbutActionPerformed

    private void resecbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resecbutActionPerformed
        if(dates.getItemCount()!=0)
        {
            try {
                String info = (String)dates.getSelectedItem();
                String[] data= info.split(":");
                String testid= data[0];
                
                JsonBuilderFactory factory = Json.createBuilderFactory(null);
                JsonArrayBuilder jsonA = factory.createArrayBuilder();
                
                jsonA = jsonA.add(factory.createObjectBuilder()
                        .add("testid",testid)                        
                );
                
                String test=jsonA.build().toString();
                test=test.replace("{", "%7B");
                test=test.replace("}", "%7D");
                URL oracle = new URL("http://localhost:8080/service/webresources/reports/finalec/"+test);
                BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
                String result,total="";
                while ((result = in.readLine()) != null)
                {
                    total+=result;
                }   
                
                JSONArray arr = new JSONArray(total);
                String username=null,idq=null,answer=null,trueanswer=null,time=null;
                DefaultTableModel dtm = new DefaultTableModel(0, 0);
                String header[] = new String[] { "Username", "Question ID", "Answer",
                "True Answer", "Time", "Exam Id" };
                dtm.setColumnIdentifiers(header);
                table1.setModel(dtm);
                
                for (int i = 0; i < arr.length(); i++)
                { // Walk through the Array.

                    JSONObject obj = arr.getJSONObject(i);
                    username=obj.getString("username");
                    idq=obj.getString("idq");
                    answer=obj.getString("answer");
                    trueanswer=obj.getString("trueanswer");
                    time=obj.getString("time");
                    dtm.addRow(new Object[] { username, idq, answer,
                    trueanswer, time, testid });

                }
            } catch (MalformedURLException ex) {
                Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JSONException ex) {
                Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_resecbutActionPerformed

    private void showallbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showallbutActionPerformed
        try {
            URL oracle = new URL("http://localhost:8080/service/webresources/reports/allres");
            BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
            String result,total="";
            while ((result = in.readLine()) != null)
            {
                total+=result;
            }
            JSONArray arr = new JSONArray(total);
            
            
            String username=null,idq=null,answer=null,trueanswer=null,time=null,examid=null;
            DefaultTableModel dtm = new DefaultTableModel(0, 0);
            String header[] = new String[] { "Username", "Question ID", "Answer",
            "True Answer", "Time", "Exam Id" };
            dtm.setColumnIdentifiers(header);
            table2.setModel(dtm);
            for (int i = 0; i < arr.length(); i++) 
             { // Walk through the Array.

                JSONObject obj = arr.getJSONObject(i);
                username=obj.getString("username");
                idq=obj.getString("idq");
                answer=obj.getString("answer");
                trueanswer=obj.getString("trueanswer");
                time=obj.getString("time");
                examid=obj.getString("examid");
                dtm.addRow(new Object[] { username, idq, answer,
                trueanswer, time, examid });
             }
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showallbutActionPerformed

    private void examineebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examineebutActionPerformed
        try {
            String user=usernametxt.getText();
            JsonBuilderFactory factory = Json.createBuilderFactory(null);
            JsonArrayBuilder jsonA = factory.createArrayBuilder();
            jsonA = jsonA.add(factory.createObjectBuilder()
                    .add("username",user)                        
            );
            String test=jsonA.build().toString();
            test=test.replace("{", "%7B");
            test=test.replace("}", "%7D");
            URL oracle = new URL("http://localhost:8080/service/webresources/reports/ru/"+test);
            BufferedReader in = new BufferedReader( new InputStreamReader(oracle.openStream()));
            String result,total="";
            while ((result = in.readLine()) != null)
            {
                total+=result;
            }      
            JSONArray arr = new JSONArray(total);
            String username=null,idq=null,answer=null,trueanswer=null,time=null,examid=null;
            DefaultTableModel dtm = new DefaultTableModel(0, 0);
            String header[] = new String[] { "Username", "Question ID", "Answer",
            "True Answer", "Time", "Exam Id" };
            dtm.setColumnIdentifiers(header);
            table3.setModel(dtm);
            for (int i = 0; i < arr.length(); i++) 
             { // Walk through the Array.

                JSONObject obj = arr.getJSONObject(i);
                username=obj.getString("username");
                idq=obj.getString("idq");
                answer=obj.getString("answer");
                trueanswer=obj.getString("trueanswer");
                time=obj.getString("time");
                examid=obj.getString("examid");
                dtm.addRow(new Object[] { username, idq, answer,
                trueanswer, time, examid });
             }
            
        } catch (MalformedURLException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_examineebutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adctxt;
    private javax.swing.JButton addac;
    private javax.swing.JPanel addadmincenter;
    private javax.swing.JPanel addexam;
    private javax.swing.JButton addexambut;
    private javax.swing.JButton addexamc;
    private javax.swing.JPanel addexamcenter;
    private javax.swing.JPanel addquestion;
    private javax.swing.JTextField address;
    private javax.swing.JPanel adduser;
    private javax.swing.JComboBox<String> answer;
    private javax.swing.JButton button;
    private javax.swing.JComboBox<String> dates;
    private javax.swing.JTextField datetxt;
    private javax.swing.JTextField ectxt;
    private javax.swing.JComboBox<String> examcenters;
    private javax.swing.JTextField examidtxt;
    private javax.swing.JButton examineebut;
    private javax.swing.JButton getecbut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField passtxt;
    private javax.swing.JTextField password;
    private javax.swing.JTextField question;
    private javax.swing.JPanel reports;
    private javax.swing.JButton resecbut;
    private javax.swing.JButton resexamidbut;
    private javax.swing.JPanel resultsalexams;
    private javax.swing.JPanel resultsexamc;
    private javax.swing.JPanel resultsexamid;
    private javax.swing.JPanel resultsexaminee;
    private javax.swing.JButton showallbut;
    private javax.swing.JButton showdatesbut;
    private javax.swing.JButton submit;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTabbedPane tpanel;
    private javax.swing.JTextField username;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
